# Permalinks
permalink:        pretty

# Setup
title: Thembi, me and my 2 cats
description:      Logbook, photos, thoughts about living on a boat with two cats
url: "https://thembi.me"
baseurl:          ""

paginate:         5

plugins:
  - jekyll-sitemap
